# Basic Python

## 1. Split this string

In [36]:
s = "Hi there Sam!"

In [37]:
s="Hi there Sam!"
s=s.split()
print(s);

['Hi', 'there', 'Sam!']


*`italicized text`*## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [38]:
planet = "Earth"
diameter = 12742

In [ ]:
planet = "Earth"
diameter = 12742
print( 'The diameter of {} is {} kilometers.' .format(planet,diameter));

The diameter of Earth is 12742 kilometers.


## 3. In this nest dictionary grab the word "hello"

In [ ]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [ ]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
print(d['k1'][3]["tricky"][3]['target'][3])

hello


# Numpy

In [ ]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [ ]:
array=np.zeros(10)
print("An array of 10 zeros:")
print(array)

An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
array=np.ones(10)*5
print("An array of 10 fives:")
print(array)

An array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 5. Create an array of all the even integers from 20 to 35

In [ ]:
import numpy as np
array=np.arange(20,36,2)
print("Array of all the even integers from 20 to 35")
print(array)

Array of all the even integers from 20 to 35
[20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
import numpy as np
x =  np.arange(0, 9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatinate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [ ]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [ ]:
import pandas as pd


In [ ]:
import pandas as pd
data = [['tom', 10], ['nick', 15], ['juli', 14]]
df = pd.DataFrame(data, columns=['Name', 'Age'])
df



Name  Age
0   tom   10
1  nick   15
2  juli   14

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [ ]:
import datetime
import pandas as pd
test_date = datetime.datetime.strptime("01-06-2022", "%d-%m-%Y")
K = 41
date_generated = pd.date_range(test_date, periods=K)
print(date_generated.strftime("%d-%m-%Y"))



Index(['01-06-2022', '02-06-2022', '03-06-2022', '04-06-2022', '05-06-2022',
       '06-06-2022', '07-06-2022', '08-06-2022', '09-06-2022', '10-06-2022',
       '11-06-2022', '12-06-2022', '13-06-2022', '14-06-2022', '15-06-2022',
       '16-06-2022', '17-06-2022', '18-06-2022', '19-06-2022', '20-06-2022',
       '21-06-2022', '22-06-2022', '23-06-2022', '24-06-2022', '25-06-2022',
       '26-06-2022', '27-06-2022', '28-06-2022', '29-06-2022', '30-06-2022',
       '01-07-2022', '02-07-2022', '03-07-2022', '04-07-2022', '05-07-2022',
       '06-07-2022', '07-07-2022', '08-07-2022', '09-07-2022', '10-07-2022',
       '11-07-2022'],
      dtype='object')


## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [ ]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [ ]:
import pandas as pd
lists = [[1, 'aaa', 22], [2, 'bbb', 25],[3, 'ccc', 24]]	
df1 = pd.DataFrame(lists, columns =['col_1', 'col_2', 'col_3'])
print(df1 )


   col_1 col_2  col_3
0      1   aaa     22
1      2   bbb     25
2      3   ccc     24
